name: Fetch Notion Blogs

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:        # Manual trigger

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: npm install @notionhq/client
        
      - name: Create Backup Directory
        run: mkdir -p src/content/blog/.backups
        
      - name: Fetch and Update Posts
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          # Add timestamp to run
          echo "Starting sync at $(date)"
          
          # Run with retries
          for i in {1..3}; do
            if node scripts/fetch-posts.js; then
              echo "Sync completed successfully"
              break
            else
              echo "Attempt $i failed, retrying in 30 seconds..."
              sleep 30
            fi
          done
