name: Fetch Notion Blogs

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:        # Manual trigger

permissions:
  contents: write          # Grants read/write access to repository contents

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          npm install @notionhq/client
          npm install dotenv
        
      - name: Create Backup Directory
        run: mkdir -p src/content/blog/.backups
        
      - name: Fetch and Update Posts
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          # Add timestamp to run
          echo "Starting sync at $(date)"
          
          # Run with retries
          for i in {1..3}; do
            if node scripts/fetch-posts.js; then
              # Configure git
              git config user.name "GitHub Action"
              git config user.email "action@github.com"
              
              # Stage and commit changes
              if [[ -n "$(git status --porcelain)" ]]; then
                echo "Changes detected, committing..."
                git add public/blog-posts.json
                git commit -m "Update blog posts from Notion [skip ci]"
                git push
              else
                echo "No changes to commit"
              fi
              
              echo "✅ Sync completed successfully"
              break
            else
              echo "❌ Attempt $i failed, retrying in 30 seconds..."
              sleep 30
              if [ $i -eq 3 ]; then
                echo "❌ All retry attempts failed"
                exit 1
              fi
            fi
          done
