name: Fetch Notion Blogs

on:
  repository_dispatch:
    types: [notion_update]
  schedule:
    - cron: '*/10 * * * *'   # Runs every 10 minutes
  workflow_dispatch:        # Manual trigger

jobs:
  update-blog:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: |
          npm install @notionhq/client
          npm install dotenv
        
      - name: Create Backup Directory
        run: mkdir -p src/content/blog/.backups
        
      - name: Fetch and Update Posts
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NODE_ENV: production
        run: |
          # Add timestamp to run
          echo "Starting sync at $(date)"
          
          # Verify environment variables
          if [ -z "$NOTION_TOKEN" ]; then
            echo "❌ NOTION_TOKEN is not set"
            exit 1
          fi
          
          if [ -z "$NOTION_DATABASE_ID" ]; then
            echo "❌ NOTION_DATABASE_ID is not set"
            exit 1
          fi
          
          # Run with retries
          for i in {1..3}; do
            if node scripts/fetch-posts.js; then
              echo "✅ Sync completed successfully"
              break
            else
              echo "❌ Attempt $i failed, retrying in 30 seconds..."
              sleep 30
              if [ $i -eq 3 ]; then
                echo "❌ All retry attempts failed"
                exit 1
              fi
            fi
          done

      - name: Commit and Push Changes
        if: success()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if [[ -n $(git status -s) ]]; then
            git add src/content/blog/
            git commit -m "Update blog posts from Notion [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
